### ISSUE TITLE
Simply does not work

### ISSUE THREAD

**Issue by Sergey80** [sjrd/scala-js-example-app#8]
sbt

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: junit#junit;4.10: configuration not found in junit#junit;4.10: 'maste
r(compile)'. Missing configuration: 'compile'. It was required from com.googleco
de.json-simple#json-simple;1.1.1 compile
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          junit:junit:4.10
[warn]            +- com.googlecode.json-simple:json-simple:1.1.1
[warn]            +- org.scala-js:scalajs-tools_2.10:0.6.2
[warn]            +- org.scala-js:scalajs-js-envs_2.10:0.6.2
[warn]            +- org.scala-js:scalajs-sbt-test-adapter_2.10:0.6.2
[warn]            +- org.scala-js:sbt-scalajs:0.6.2 (scalaVersion=2.10, sbtVersi
on=0.13) (C:\Users\sstarodu\Desktop\scala-js-example-app-master\project\build.sb
t#L1-2)
[warn]            +- default:scala-js-example-app-master-build:0.1-SNAPSHOT (sca
laVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: junit#junit;4.10: configuration not
 found in junit#junit;4.10: 'master(compile)'. Missing configuration: 'compile'.
 It was required from com.googlecode.json-simple#json-simple;1.1.1 compile
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:278)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:175)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:157)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:128)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:64)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRet
ries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:

**Comment by Sergey80** [comment]
I guess because of Java 8 installed on my machine

**Comment by sjrd** [comment]
Everything's supposed to work with Java 8. We test with Java 8 in our CI.
A Resolve error might be transient though, if the servers are down or overloaded. Have you retried a couple of minutes later?

**Comment by Sergey80** [comment]
i guess I'm under firewall. will test it from home today.

**Comment by Sergey80** [comment]
yeah.. firewall..  but maybe it should be put alternative repos for junit.
